# Generated by Django 5.2.4 on 2025-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('texto', models.TextField(verbose_name='texto')),
                ('data_pub', models.DateField(verbose_name='data')),
                ('imagem_url', models.URLField(verbose_name='imagem')),
            ],
        ),
    ]
