# Generated by Django 5.2.4 on 2025-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=99)),
                ('criador', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=99)),
                ('github', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data_pub',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
