# Generated by Django 5.2.4 on 2025-08-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_alter_post_data_pub_alter_post_imagem_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
