# Generated by Django 5.2.4 on 2025-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('status', models.CharField(choices=[('em andamento', 'em andamento'), ('finalizada', 'finalizada'), ('pendente', 'pendente')], default='pendente', verbose_name='status')),
                ('prazo', models.DateField(verbose_name='prazo')),
            ],
        ),
    ]
